import './globals.css'

export const metadata = {
  title: 'Simple Upload Images',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="stylesheet preload" href="path/to/stylesheet" as="style" />
      <body>{children}</body>
    </html>
  )
}
